### ISSUE TITLE
Unable to find starter template for https://github.com/backand/backand-ionic-starter

### ISSUE THREAD

**Issue by SKnewIonic** [backand/backand-ionic-starter#2]
Hii

When I try to create a new app using the backand-ionic-starter, its throwing me the unable to find template error...

I tried to download it and tried to create from local, still doesnt work.. can someone pls help..

Thanks

**Comment by kornatzky** [comment]
Recent changes in Ionic, unrelated to Backand, prevent creating a project from a custom template. Please follow the instructions in the README. You need to create an Ionic 2 project from tabs template and then replace files from  the starter, as instructed in the README.
